import { readFileSync } from "fs";
import { join } from "path";
import { describe, expect, test } from "bun:test";
import { yarnLockParserInternals } from "bun:internal-for-testing";
const { parse } = yarnLockParserInternals;

describe("yarn lockfile v1", () => {
  test("parsing", () => {
    const result = parse(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
package-1@^1.0.0:
  version "1.0.3"
  resolved "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
package-2@^2.0.0:
  version "2.0.1"
  resolved "https://registry.npmjs.org/package-2/-/package-2-2.0.1.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
  dependencies:
    package-4 "^4.0.0"
package-3@^3.0.0:
  version "3.1.9"
  resolved "https://registry.npmjs.org/package-3/-/package-3-3.1.9.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
  dependencies:
    package-4 "^4.5.0"
package-4@^4.0.0, package-4@^4.5.0:
  version "4.6.3"
  resolved "https://registry.npmjs.org/package-4/-/package-4-2.6.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
`);

    expect(result).toEqual([
      { comment: "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." },
      { comment: "yarn lockfile v1" },
      {
        block: {
          dependencies: [],
          packages: [
            {
              name: "package-1",
              version: "^1.0.0",
            },
          ],
          resolved:
            "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
          version: "1.0.3",
          optionalDependencies: [],
          integrity: null,
        },
      },
      {
        block: {
          dependencies: [
            {
              name: "package-4",
              version: "^4.0.0",
            },
          ],
          packages: [
            {
              name: "package-2",
              version: "^2.0.0",
            },
          ],
          resolved:
            "https://registry.npmjs.org/package-2/-/package-2-2.0.1.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
          version: "2.0.1",
          optionalDependencies: [],
          integrity: null,
        },
      },
      {
        block: {
          dependencies: [
            {
              name: "package-4",
              version: "^4.5.0",
            },
          ],
          packages: [
            {
              name: "package-3",
              version: "^3.0.0",
            },
          ],
          resolved:
            "https://registry.npmjs.org/package-3/-/package-3-3.1.9.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
          version: "3.1.9",
          optionalDependencies: [],
          integrity: null,
        },
      },
      {
        block: {
          dependencies: [],
          packages: [
            {
              name: "package-4",
              version: "^4.0.0",
            },
            {
              name: "package-4",
              version: "^4.5.0",
            },
          ],
          resolved:
            "https://registry.npmjs.org/package-4/-/package-4-2.6.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
          version: "4.6.3",
          optionalDependencies: [],
          integrity: null,
        },
      },
    ]);
  });

  test("entry with integrity", () => {
    const result = parse(`
undici@^5.28.4:
  version "5.28.4"
  resolved "https://registry.yarnpkg.com/undici/-/undici-5.28.4.tgz#6b280408edb6a1a604a9b20340f45b422e373068"
  integrity sha512-72RFADWFqKmUb2hmmvNODKL3p9hcB6Gt2DOQMis1SEBaV6a4MH8soBvzg+95CYhCKPFedut2JY9bMfrDl9D23g==
  dependencies:
    "@fastify/busboy" "^2.0.0"
`);

    expect(result).toEqual([
      {
        block: {
          dependencies: [
            {
              name: "@fastify/busboy",
              version: "^2.0.0",
            },
          ],
          packages: [
            {
              name: "undici",
              version: "^5.28.4",
            },
          ],
          integrity: "sha512-72RFADWFqKmUb2hmmvNODKL3p9hcB6Gt2DOQMis1SEBaV6a4MH8soBvzg+95CYhCKPFedut2JY9bMfrDl9D23g==",
          resolved: "https://registry.yarnpkg.com/undici/-/undici-5.28.4.tgz#6b280408edb6a1a604a9b20340f45b422e373068",
          version: "5.28.4",
          optionalDependencies: [],
        },
      },
    ]);
  });

  test("entry with optional dependencies", () => {
    const result = parse(`
extract-zip@^2.0.1:
  version "2.0.1"
  resolved "https://registry.yarnpkg.com/extract-zip/-/extract-zip-2.0.1.tgz#663dca56fe46df890d5f131ef4a06d22bb8ba13a"
  integrity sha512-GDhU9ntwuKyGXdZBUgTIe+vXnWj0fppUEtMDL0+idd5Sta8TGpHssn/eusA9mrPr9qNDym6SxAYZjNvCn/9RBg==
  dependencies:
    debug "^4.1.1"
    get-stream "^5.1.0"
    yauzl "^2.10.0"
  optionalDependencies:
    "@types/yauzl" "^2.9.1"
`);

    expect(result).toEqual([
      {
        block: {
          dependencies: [
            {
              name: "debug",
              version: "^4.1.1",
            },
            {
              name: "get-stream",
              version: "^5.1.0",
            },
            {
              name: "yauzl",
              version: "^2.10.0",
            },
          ],
          integrity: "sha512-GDhU9ntwuKyGXdZBUgTIe+vXnWj0fppUEtMDL0+idd5Sta8TGpHssn/eusA9mrPr9qNDym6SxAYZjNvCn/9RBg==",
          optionalDependencies: [
            {
              name: "@types/yauzl",
              version: "^2.9.1",
            },
          ],
          packages: [
            {
              name: "extract-zip",
              version: "^2.0.1",
            },
          ],
          resolved:
            "https://registry.yarnpkg.com/extract-zip/-/extract-zip-2.0.1.tgz#663dca56fe46df890d5f131ef4a06d22bb8ba13a",
          version: "2.0.1",
        },
      },
    ]);
  });

  test("entry without dependencies", () => {
    const result = parse(`
"@aashutoshrathi/word-wrap@^1.2.3":
  version "1.2.6"
  resolved "https://registry.yarnpkg.com/@aashutoshrathi/word-wrap/-/word-wrap-1.2.6.tgz#bd9154aec9983f77b3a034ecaa015c2e4201f6cf"
  integrity sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==
`);

    expect(result).toEqual([
      {
        block: {
          dependencies: [],
          integrity: "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
          optionalDependencies: [],
          packages: [
            {
              name: "@aashutoshrathi/word-wrap",
              version: "^1.2.3",
            },
          ],
          resolved:
            "https://registry.yarnpkg.com/@aashutoshrathi/word-wrap/-/word-wrap-1.2.6.tgz#bd9154aec9983f77b3a034ecaa015c2e4201f6cf",
          version: "1.2.6",
        },
      },
    ]);
  });

  test("entry with package alias", () => {
    const result = parse(`
"prettier-2@npm:prettier@^2":
  version "2.8.8"
  resolved "https://registry.yarnpkg.com/prettier/-/prettier-2.8.8.tgz#e8c5d7e98a4305ffe3de2e1fc4aca1a71c28b1da"
  integrity sha512-tdN8qQGvNjw4CHbY+XXk0JgCXn9QiF21a55rBe5LJAU+kDyC4WQn4+awm2Xfk2lQMk5fKup9XgzTZtGkjBdP9Q==
`);

    expect(result).toEqual([
      {
        block: {
          dependencies: [],
          integrity: "sha512-tdN8qQGvNjw4CHbY+XXk0JgCXn9QiF21a55rBe5LJAU+kDyC4WQn4+awm2Xfk2lQMk5fKup9XgzTZtGkjBdP9Q==",
          optionalDependencies: [],
          packages: [
            {
              name: "prettier-2",
              version: "npm:prettier@^2",
            },
          ],
          resolved:
            "https://registry.yarnpkg.com/prettier/-/prettier-2.8.8.tgz#e8c5d7e98a4305ffe3de2e1fc4aca1a71c28b1da",
          version: "2.8.8",
        },
      },
    ]);
  });

  describe("lockfile snapshots", () => {
    test("react", () => {
      const reactLockfile = readFileSync(join(import.meta.dir, "react.yarn.lock")).toString();
      const output = parse(reactLockfile);
      expect(output).not.toBeNull();
      expect(output).toMatchSnapshot();
    });
  });
});
